web:
  build: .
  command: 'bash -c ''java $JVM_OPTS -cp target/simba.jar clojure.main -m simba.core'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
